<a href="https://colab.research.google.com/github/NuryaFahruRosyidin2406/Dicoding_Learn-ML/blob/main/Membuat_Model_untuk_Klasifikasi_Dua_Kelas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd

url = 'https://github.com/NuryaFahruRosyidin2406/Dicoding_Learn-ML/raw/main/Dataset/Membuat%20Model%20untuk%20Klasifikasi%20Dua%20Kelas/citrus.csv'
# df = pd.read_csv('citrus.csv')
df = pd.read_csv(url, encoding='utf-8')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [42]:
df.head(10000)

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [43]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

<ipython-input-43-e9c3e7476411>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'orange'] = 0
<ipython-input-43-e9c3e7476411>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'grapefruit'] = 1


In [44]:
df.head(10000)

name  diameter  weight  red  green  blue
0       0      2.96   86.76  172     85     2
1       0      3.91   88.05  166     78     3
2       0      4.42   95.17  156     81     2
3       0      4.47   95.60  163     81     4
4       0      4.48   95.76  161     72     9
...   ...       ...     ...  ...    ...   ...
9995    1     15.35  253.89  149     77    20
9996    1     15.41  254.67  148     68     7
9997    1     15.59  256.50  168     82    20
9998    1     15.92  260.14  142     72    11
9999    1     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [45]:
dataset = df.values
dataset

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

In [46]:
# pilih 5 kolom terakhir sebagai atribut
X = dataset[:,1:6]
X
# bilangan sebelum koma untuk memilih baris pada dataframe
# bilangan setelah koma untuk memilih kolom pada dataframe

array([[2.96, 86.76, 172, 85, 2],
       [3.91, 88.05, 166, 78, 3],
       [4.42, 95.17, 156, 81, 2],
       ...,
       [15.59, 256.5, 168, 82, 20],
       [15.92, 260.14, 142, 72, 11],
       [16.45, 261.51, 152, 74, 2]], dtype=object)

In [47]:
y = dataset[:,0]
y

array([0, 0, 0, ..., 1, 1, 1], dtype=object)

In [48]:
# Normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [49]:
# pisahkan data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [50]:
import numpy as np

Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [51]:
from keras.models import Sequential
from keras.layers import Dense
from keras.regularizers import l2

In [52]:
model = Sequential([
                    Dense(32, activation='relu', input_shape=(5,)),
                    Dense(32, activation='relu', kernel_regularizer=l2(0.01)),
                    Dense(1, activation='sigmoid'),])

In [53]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [54]:
model.fit(X_train, Y_train, epochs=150)

Epoch 1/150
219/219 [==============================] - 1s 2ms/step - loss: 0.9785 - accuracy: 0.7680
Epoch 2/150
219/219 [==============================] - 0s 2ms/step - loss: 0.8921 - accuracy: 0.8890
Epoch 3/150
219/219 [==============================] - 0s 2ms/step - loss: 0.7946 - accuracy: 0.9093
Epoch 4/150
219/219 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.9157
Epoch 5/150
219/219 [==============================] - 0s 2ms/step - loss: 0.5995 - accuracy: 0.9176
Epoch 6/150
219/219 [==============================] - 0s 2ms/step - loss: 0.5279 - accuracy: 0.9206
Epoch 7/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4775 - accuracy: 0.9226
Epoch 8/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4416 - accuracy: 0.9221
Epoch 9/150
219/219 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.9234
Epoch 10/150
219/219 [==============================] - 0s 2ms/step - loss: 0.3936 - accura

In [55]:
model.evaluate(X_test, Y_test)
# elemen pertama adalah loss dan elemen kedua adalah akurasi

94/94 [==============================] - 0s 2ms/step - loss: 0.1780 - accuracy: 0.9347


[0.17797549068927765, 0.9346666932106018]